name: Auto Destroy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write
  id-token: write
  pull-requests: write
  issues: write

jobs:
  destroy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, '[CLEANUP]') || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
      - name: Terraform Init
        id: init
        working-directory: ./cicd_bootstrap
        run: terraform init -backend-config=../env/backend.tfvars
      - name: Terraform Destroy
        id: destroy
        working-directory: ./cicd_bootstrap
        run: terraform destroy -no-color -input=false -var-file ../env/project.tfvars -var-file conf/github_actions.tfvars -auto-approve
        continue-on-error: false
